<map id="pylo.vendors.urllib3.exceptions.LocationValueError" name="pylo.vendors.urllib3.exceptions.LocationValueError">
<area shape="rect" id="node1" title=" " alt="" coords="379,39,577,80"/>
<area shape="rect" id="node5" href="$classpylo_1_1vendors_1_1urllib3_1_1exceptions_1_1_location_parse_error.html" title=" " alt="" coords="625,5,824,47"/>
<area shape="rect" id="node6" href="$classpylo_1_1vendors_1_1urllib3_1_1exceptions_1_1_u_r_l_scheme_unknown.html" title=" " alt="" coords="625,71,824,112"/>
<area shape="rect" id="node2" title=" " alt="" coords="190,17,273,43"/>
<area shape="rect" id="node3" href="$classpylo_1_1vendors_1_1urllib3_1_1exceptions_1_1_h_t_t_p_error.html" title=" " alt="" coords="132,68,331,109"/>
<area shape="rect" id="node4" title=" " alt="" coords="5,75,84,102"/>
<area shape="rect" id="node7" href="$classpylo_1_1vendors_1_1urllib3_1_1exceptions_1_1_proxy_scheme_unknown.html" title=" " alt="" coords="872,71,1071,112"/>
</map>
